members_only/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root              'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
end

members_only/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

members_only/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

members_only/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  attr_accessor :token_digest
  before_create :set_token
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
  # secretely made virtual password and password_confirmation
  def refresh_token
    token=SecureRandom.urlsafe_base64
    token_digest=Digest::SHA1.hexdigest(token.to_s)
  end


private
  def set_token
    token=SecureRandom.urlsafe_base64
    token_digest=Digest::SHA1.hexdigest(token.to_s)
    self.remember_token= token_digest
  end

end

members_only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login(user)
    user.update_attribute(:remember_token, user.refresh_token)
    cookies.permanent[:remember_token]=user.remember_token
  end

  def current_user
    if cookies[:remember_token]
      @current_user= User.find_by(remember_token: cookies[:remember_token])
    else
      @current_user=nil
    end
  end

  def current_user=(value)
    @current_user=value
  end

  def sign_out
    cookies.delete(:remember_token)
    @current_user=nil
  end

  def signed_in?
    redirect_to login_url unless current_user
  end

end

members_only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in?, only: [:new, :create]
  before_action :current_user, only: [:index]
  def new
    @post=Post.new
  end

  def create
    @post=Post.new(post_params)
    @post.user_id=params[:user_id]
    if @post.save
      flash[:success]="Successfully saved post"
      redirect_to posts_url
    else
      flash.now[:danger]="Try again"
      render 'new'
    end
  end

  def index
    @post=Post.all
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end



end

members_only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user=User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      current_user
      flash[:success]="You are now logged in."
      redirect_to users_show_path
    else
      flash.now[:danger]="Login failed, try again."
      render 'new'
    end
  end

  def destroy

    sign_out
    flash[:success]="You are now logged out."
    redirect_to root_url
  end

end

members_only/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

members_only/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in?, only: [:show]
  def show
    @user=User.find_by(remember_token: cookies[:remember_token])
  end
end

members_only/app/helpers/application_helper.rb
module ApplicationHelper
end

members_only/app/helpers/posts_helper.rb
module PostsHelper
end

members_only/app/helpers/sessions_helper.rb
module SessionsHelper
end

members_only/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

members_only/app/helpers/users_helper.rb
module UsersHelper
end

members_only/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Member's Club</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <h1>The Member's Club. </h1>
<%= link_to "Home", root_url %>
<%= link_to "Log In", login_path %>
<%= link_to "Log Out", logout_path, method: :delete %>
<%= link_to "Posts", posts_path %>
<%= link_to "New Post", new_post_path %>
<%= link_to "Profile", users_show_path(@user) %>

  <body>
    <%= yield %>
  </body>
</html>

members_only/app/views/posts/index.html.erb
<h1>The Gossip Vine.</h1>

<% @post.each do |post|%>
<div>
<%= post.title %></br></br>
<%= post.body %></br>
  <% if @current_user %>
    <%="Author: #{User.find_by(id: post.user_id).name}" %>
    <% else %>
    <%= "Author: Hidden" %>
  <% end %>
</div>
  </br></br>
<% end %>

members_only/app/views/posts/new.html.erb
<h1>Submit your secrets below!</h1>

<%= form_for @post do |f| %>
<%=f.label :title %></br>
<%=f.text_field :title %></br>
<%=f.label :body %></br>
<%=f.text_field :body %></br>
<%= hidden_field_tag :user_id, @current_user.id %></br>
<%= f.submit %>
<% end %>

members_only/app/views/users/show.html.erb
<h1><%= "#{@user.name}" %>'s Profile</h1>
Hi <%= "#{@user.name}" %></br>
<%= link_to "View Gossip", posts_path %>